### ISSUE TITLE
GMSSL engine使用咨询

### ISSUE THREAD

**Issue by YangShizhao** [xianrenqiu/gmssl_engine#1]
你好，我最近也在看GMSSL的相关资料，但是我编译运行完了GMSSL的代码后，才发现好像不会用engine，我搜索了一些信息，发现是GMSSL里并没有原生支持engine的代码，并不是像官网声称的那样可以直接支持SKF标准接口，需要自己做开发对接。
但是我对GMSSL的代码刚接触，不是很了解具体要在哪个地方做开发对接，请问可以跟您请教下嘛？

**Comment by xianrenqiu** [comment]
@YangShizhao 抱歉，这条消息漏掉了，我想您的问题应该已经解决了，如果后面有其他内容需要交流，可以发我邮件(xianrenqiu90@qq.com)；
